[package]
name = "ash-cube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.33.3"
ash-window = "0.7.0"
nalgebra = "0.29.0"
once_cell = "1.8.0"
winit = "0.25.0"
